/// For values automatically generated by database.
///
/// It works similar to [Option] but conveys a clearer meaning.
#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum AutoGen<T> {
    /// The value is already provided by the database
    Known(T),
    /// The value is not yet provided by the database
    Unknown,
}

impl<T: Copy> Copy for AutoGen<T> {}

impl<T: PartialEq> PartialEq for AutoGen<T> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            // We do not assume different unknowns are the same value
            (Self::Unknown, other::Unknown) => false,
            (Self::Known(l0), other::Known(r0)) => l0 == r0,
            _ => core::mem::discriminant(self) == core::mem::discriminant(other),
        }
    }
}
