-- Add migration script here
CREATE TABLE IF NOT EXISTS lemma (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    tarikh_masuk TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nama TEXT NOT NULL
)