[package]
name = "schema"
version = "1.0.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }

[dev-dependencies]
serde_json = "1.0.135"
